import React from 'react';
import './globals.css';
import localFont from 'next/font/local';

const mainFont = localFont({
  src: '../fonts/PretendardVariable.woff2',
  style: 'normal',
  variable: '--mainfont',
  display: 'swap',
  preload: true,
  fallback: ['sans-serif'],
});

/**
 * TODO:metadata 보완
 */
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.ReactNode {
  return (
    <html lang="en" className={mainFont.className}>
      <body>{children}</body>
    </html>
  );
}
